(maint) Upgrade Docker Alpine container 3.8 -> 3.9
 - Apparently TravisCI has problems serving Alpine 3.8 with buildkit, so
   upgrade to Alpine 3.9, which Travis has available.

   This is not without its challenges, because Alpine 3.9 ships with GCC
   8.3 instead of GCC 6.4 -- and at the very least, Leatherman does not
   compile with GCC 8.3 because one of its dependencies, RapidJSON, does
   not yet compile with newer GCC versions.

   RapidJSON is now nearly 4 years waiting for a next release (that adds
   GCC 8.3 compatibility), with no release in sight:
	 https://github.com/Tencent/rapidjson/issues/1006

   So without a custom fork, upgrading RapidJSON is not an easy option.

- Alpine started shipping packages gcc6, libstdc++6 and g++6 with Alpine
  3.9, but attempts to install g++6 with apk yields problems with
  unsatisfiable constraints like:

  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
  fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
  ERROR: unsatisfiable constraints:
    libstdc++-8.3.0-r0:
      breaks: g++6-6.4.0-r9[libstdc++=6.4.0-r9]
      satisfies: gcc-8.3.0-r0[so:libstdc++.so.6]
    gcc-8.3.0-r0:
      breaks: g++6-6.4.0-r9[gcc=6.4.0-r9]

  One way to workarond this problem is to use the --force-broken-world
  switch to install g++6, but this causes parts of boost to be purged
  and conflicts with other packages, so additional work would need to be
  done to straighten out the build system.

  Another simpler option is to pin gcc and g++ packages to the Alpine
  3.8 versions and to use that repo to install those packages from.
  Once those dependencies are set, all other dependencies can be
  installed from the 3.9 repos as usual, without resorting to
  --force-broken-world.

- NOTE: All packages could be installed with a single apk add, but by
  breaking them apart, we ensure that only g++ and gcc from the 3.8
  version of Alpine are installed. APK will otherwise install packages
  with higher numbers from the 3.8 repo rather than installing them
  from the 3.9 repo, which may not prevent build failures, but can cause
  runtime issues, such as problems with SSL when using `puppet module
  install`:

  Notice: Downloading from https://forgeapi.puppet.com ...
  Error: Could not connect to https://forgeapi.puppet.com
    There was a network communications problem
      The error we caught said 'SSL_CTX_set_ecdh_auto'